name = "EpiRegistry"
uuid = "26539dc5-a174-43eb-a619-f6f40fb70910"
repo = "https://github.com/alexpkeil1/EpiRegistry.git"

[packages]
0b759ec4-1e0e-48f5-a120-aab12489aed1 = { name = "Qgcomp", path = "Q/Qgcomp" }
edbbf5c1-874b-40a5-8c9f-d8fc918aacaa = { name = "LSurvival", path = "L/LSurvival" }
